# Generated by Django 4.1.2 on 2022-11-20 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_placa', models.FloatField(default=0)),
                ('nome_popular', models.CharField(max_length=255)),
                ('nome_cientifico', models.CharField(max_length=255)),
                ('dap', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('laudo', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tree')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
