# Generated by Django 4.1.2 on 2022-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=255)),
                ('nome_cientifico', models.CharField(max_length=255)),
                ('DAP', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('data_da_coleta', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
