# Generated by Django 4.1.2 on 2022-10-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tree_laudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='DAP',
            new_name='dap',
        ),
    ]
