# Generated by Django 4.1.2 on 2022-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_dap_tree_dap"),
    ]

    operations = [
        migrations.RemoveField(model_name="tree", name="data_da_coleta",),
        migrations.AddField(
            model_name="tree", name="N_placa", field=models.FloatField(default=0),
        ),
    ]
