# Generated by Django 4.1.2 on 2023-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='imagem',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='altura',
            field=models.FloatField(),
        ),
    ]
