# Generated by Django 4.1.2 on 2023-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tree_imagem_alter_tree_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='specialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tree',
            name='plantado_por',
            field=models.CharField(default='DCTA', max_length=100),
        ),
    ]
